# -*- coding: utf-8 -*-
"""Recognition and segmentation, tested with our own voice.

There is no microphone on this machine. Rather than ship untested recognition
and hope, the test signal is generated by the TTS that was built first: Piper
speaks a known sentence, and Vosk has to read it back. The loop closes with no
hardware at all.

This is not a substitute for a real microphone in a real room - synthetic
speech has no background noise, no reverb and no distance - so what it proves
is that the wiring, framing, rates, segmentation and grammar handling are all
correct. Acoustic performance is a separate question, answered when the mic
arrives.
"""
import os
import sys
import time

os.environ.setdefault("OPENBLAS_CORETYPE", "ARMV8")

# vosk's libvosk.so needs a newer libstdc++ than this box ships, kept in lib/.
# LD_LIBRARY_PATH must be set BEFORE the process starts - the dynamic linker
# reads it at exec time, so os.environ.setdefault() here does nothing at all.
# This test appeared to pass for a while purely because the variable happened
# to be set on the command line; run on its own it failed to load vosk.
# Re-exec once with the right environment rather than requiring the caller to
# know.
_LIB = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "lib")
if os.path.isdir(_LIB) and _LIB not in os.environ.get("LD_LIBRARY_PATH", ""):
    os.environ["LD_LIBRARY_PATH"] = _LIB + ":" + os.environ.get("LD_LIBRARY_PATH", "")
    os.execv(sys.executable, [sys.executable] + sys.argv)

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np

from tekdromo.voice import io as vio, pcm, stt, tts, vad

FAIL = []


def check(name, cond, extra=""):
    print("  %-52s %s%s" % (name, "OK" if cond else "FAIL",
                            "" if cond else "  <- " + str(extra)))
    if not cond:
        FAIL.append(name)


def overlap(said, heard):
    """Fraction of the expected words that came back."""
    want = [w for w in said.lower().replace(",", "").replace(".", "").split()]
    got = set(heard.lower().split())
    if not want:
        return 0.0
    return sum(1 for w in want if w in got) / float(len(want))


if not os.path.isdir(stt.DEFAULT_MODEL):
    print("  no speech model - skipping")
    sys.exit(2)

print("  loading voice and recogniser...")
voice = tts.load("piper")
t0 = time.time()
free = stt.Recogniser()
wake = stt.Recogniser(grammar=stt.WAKE_GRAMMAR)
print("  ready in %.2fs" % (time.time() - t0))


def speak(text):
    """Piper -> the pipeline's 16 kHz contract, exactly as a mic would deliver."""
    samples, rate = voice.synth(text)
    return vio.ArraySource(samples, rate).all()


def rtf(rec, audio, runs=3):
    """Real-time factor of RECOGNITION ONLY.

    Synthesis must happen outside the timed region - timing speak()+transcribe()
    and dividing by the audio length measures Piper as well and reported 1.08x
    for a wake word that actually costs a fraction of that. The first call also
    pays one-off warm-up, so it is discarded.
    """
    rec.transcribe(audio)                       # warm up, discard
    secs = len(audio) / float(pcm.RATE)
    best = None
    for _ in range(runs):
        t0 = time.time()
        rec.transcribe(audio)
        d = (time.time() - t0) / secs
        best = d if best is None else min(best, d)
    return best


# -- straight recognition --------------------------------------------------
PHRASES = [
    "turn on the kitchen light",
    "what time is it",
    "play some music please",
]
for p in PHRASES:
    audio = speak(p)
    heard = free.transcribe(audio)
    ov = overlap(p, heard)
    print("    said  %-30r" % p)
    print("    heard %-30r  %.0f%% of words" % (heard, ov * 100))
    check("recognised: %s" % p, ov >= 0.6, "%.0f%%" % (ov * 100))

# -- speed -----------------------------------------------------------------
audio = speak("this is a longer sentence used to measure how fast the "
              "recogniser runs on this board")
free_rtf = rtf(free, audio)
print("    free decode  : %.2fx real-time" % free_rtf)
check("recognition is faster than real time", free_rtf < 1.0,
      "%.2fx" % free_rtf)

# -- the wake word ---------------------------------------------------------
hit = wake.transcribe(speak("hey tek"))
check("wake grammar hears the wake word", stt.heard_wake(hit), repr(hit))

miss = wake.transcribe(speak("the weather is quite nice today thank you"))
check("wake grammar does NOT fire on ordinary conversation",
      not stt.heard_wake(miss), repr(miss))

# Every listed spelling must actually fire. A grammar entry containing a word
# the model has no pronunciation for is SILENTLY DEAD - Vosk warns and carries
# on - so an unusable variant looks configured and only ever loses wake-ups.
# That already happened once here with "tekdromo".
for variant in stt.WAKE_WORDS:
    got = wake.transcribe(speak(variant))
    check("wake grammar fires on its own variant %r" % variant,
          stt.heard_wake(got), repr(got))

# The variants exist for recall, so they must not cost precision. These are
# the near neighbours: "okay then lets go" decodes as "okay deck [unk]", which
# is exactly why "okay deck" is NOT one of the listed spellings.
#
# "high tech" is deliberately NOT in this list. Measured 5 times each:
#
#   "high tech gadgets"        fired 0/5
#   "this is high tech stuff"  fired 1/5
#   "high tech" on its own     fired 5/5   <- always
#
# It is a homophone of the wake word. No grammar can separate them, and
# pretending otherwise just produces a flaky test - this one failed twice
# under load before being measured, because Piper's own output varies slightly
# run to run. The collision is accepted: someone has to say "high tech" as a
# complete utterance, and the cost is that it listens for a moment.
#
# HOW FLAKY, measured rather than felt: 14 consecutive runs on this box gave 11
# passes and 3 failures, the failures clustered in one window and spread across
# TWO different assertions - this one, and "first segment survives segmentation
# intact" further down. A following 8 runs at a HIGHER load average (4.99
# against 4.26 when it failed) passed 8 of 8, so it is not CPU contention,
# which was the obvious theory and the wrong one.
#
# Both failing assertions share a dependency: they compare what Vosk decodes
# from audio Piper has just synthesised, so they inherit any variation in
# either. Treat a single failure here as a prompt to re-run, and only chase it
# if it repeats - but do NOT quietly delete the assertions, because they are
# the ones guarding precision against the wake-word variants.
# The garbage model is what makes this list passable at all. A constrained
# grammar must map every sound onto its vocabulary, so with no decoys ordinary
# speech has nowhere to go except the wake word. Measured on twenty lines of
# family conversation: no decoys fired on 2 of 20 ("okay technically it's not"
# -> "okay tek", "hey take a look at this" -> "hey tek"); with decoys, 0 of 20,
# and no recall lost on 5 real wake words.
check("the grammar carries decoys that are NOT accepted",
      all(d not in stt.WAKE_WORDS for d in stt.WAKE_DECOYS)
      and len(stt.WAKE_DECOYS) >= 6)
check("'okay' is a decoy, not a wake word - it is the commonest word in a "
      "kitchen", "okay" in stt.WAKE_DECOYS
      and not any(w.startswith(("ok ", "okay ")) for w in stt.WAKE_WORDS))
for phrase in ("[unk] okay tek [unk]", "hey take", "okay tech", "technically"):
    check("does NOT wake on %r" % phrase, not stt.heard_wake(phrase))

# Whole words, not substrings. A substring test made the garbage model fire the
# very thing it exists to absorb - twelve false wakes in twelve hours, every one
# a decoy read as an accept word because it starts with the same letters.
for phrase in ("hey technically", "hey technically technically", "hey text",
               "the hey technically"):
    check("a decoy CONTAINING a wake word does not fire: %r" % phrase,
          not stt.heard_wake(phrase))
for phrase in ("hey tek", "hey tek [unk]", "[unk] hey tek [unk]", "hey tech"):
    check("the real wake word still fires: %r" % phrase,
          stt.heard_wake(phrase))

for ordinary in ("take the bins out", "check the oven please",
                 "hey there how are you",
                 "okay then lets go", "hey mum"):
    got = wake.transcribe(speak(ordinary))
    check("no false wake on %r" % ordinary[:22],
          not stt.heard_wake(got), repr(got))

wake_audio = speak("hey tek")
wake_rtf = rtf(wake, wake_audio)
print("    wake spotting: %.2fx real-time  (%.0f%% of one core, always on)"
      % (wake_rtf, wake_rtf * 100))
check("wake spotting is cheap enough to run always", wake_rtf < 0.8,
      "%.2fx" % wake_rtf)
check("the wake grammar is cheaper than free decoding",
      wake_rtf < free_rtf, "%.2fx vs %.2fx" % (wake_rtf, free_rtf))

check("strip_wake removes the trigger",
      stt.strip_wake("hey tek what time is it") == "what time is it",
      stt.strip_wake("hey tek what time is it"))
check("strip_wake leaves a bare command alone",
      stt.strip_wake("what time is it") == "what time is it")

# -- segmentation ----------------------------------------------------------
# Two utterances with a gap: the segmenter must return two, not one or three.
gap = pcm.silence(int(pcm.RATE * 1.2))
a, b = speak("turn on the light"), speak("what time is it")
stream = np.concatenate([pcm.silence(pcm.RATE // 2), a, gap, b,
                         pcm.silence(pcm.RATE // 2)])
# adaptive=False: this fixture is two clean utterances with digital silence
# between them, which has no room floor to track. The adaptive gate is for
# CONTINUOUS noise and is measured in tools/, not here.
segs = list(vad.Segmenter(adaptive=False).segments(vio.ArraySource(stream)))
print("    segmenter found %d utterances in a 2-utterance stream" % len(segs))
check("segmenter splits on the silence between utterances", len(segs) == 2,
      len(segs))

if len(segs) == 2:
    # The pre-roll is what stops the first phoneme being clipped; without it
    # the wake word never matches.
    h1 = free.transcribe(segs[0])
    check("first segment survives segmentation intact",
          overlap("turn on the light", h1) >= 0.6, repr(h1))
    check("segments are shorter than the whole stream (silence was dropped)",
          sum(len(s) for s in segs) < len(stream) * 0.9)

check("pure silence produces no utterances",
      len(list(vad.Segmenter().segments(
          vio.ArraySource(pcm.silence(pcm.RATE * 2))))) == 0)

ratio = vad.speech_ratio(vio.ArraySource(np.concatenate(
    [pcm.silence(pcm.RATE), a])))
print("    speech ratio of half-silence clip: %.2f" % ratio)
check("VAD distinguishes speech from silence", 0.05 < ratio < 0.95, ratio)

print("VOICE STT " + ("OK" if not FAIL else "FAILED: " + ", ".join(FAIL)))
sys.exit(1 if FAIL else 0)
